// fra-react/pagina-react/src/components/Body.js
import React from 'react';/*Esta línea importa la biblioteca React y 
hace que esté disponible en este archivo.*/

function Body() { /*Aqui definimos una función llamada body que al igual que el header
se convierte en un componente*/
  return ( /*la función nos devuelve los elementos de la interfaz*/

  /*Aqui creamos un contenedor que contiene un titulo y un parrafo dentro de un div
  que tiene una clase llamada container que nos permite hacer mención de nuestro div 
  en la app*/
    <div class="container">
      <h1>Bienvenido, esta es una pagina web minimalista hecha con React</h1>
      <p>Este es el contenido de la Aplicación en React</p>
    </div>
  );
}
/*Aqui al final definos la exportación de nuestro 
componente Body para usarlo en nuestra app*/
export default Body;

// fra-angular/pagina-angular/src/app/body/body.component.ts
// Importamos el módulo Component desde Angular core
import { Component } from '@angular/core';

// Usamos el decorador Component para configurar este componente
@Component({
  // Selector del componente que se usará en la vista HTML
  selector: 'app-body',
  // Ruta del archivo HTML que representa la vista del componente
  templateUrl: './body.component.html',
  // Rutas a archivos CSS para estilizar el componente
  styleUrls: ['./body.component.css']
})
/* Definimos la clase del componente BodyComponent que puede ser 
usado o mencionado en cualquier parte de nuestra aplicación*/
export class BodyComponent {

}

<!--Aqui creamos un contenedor que contiene un titulo y un parrafo
  dentro de un div que tiene una clase llamada container que nos
  permite hacer mención de nuestro div en la app-->
<div class="container">
  <h1>Bienvenido, esta es una pagina web minimalista hecha con Angular</h1>
  <p>Este es el contenido de la Aplicación en Angular</p>
</div>
